program: q_network.py
name: cartpole
method: bayes
metric:
  goal: maximize
  name: eval_reward
parameters:
  n_steps:
    value: 100000
  learning_rate:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-1
  target_update_frequency:
    distribution: int_uniform
    min: 100
    max: 100000
  batch_size:
    distribution: int_uniform
    min: 8
    max: 128
  episode_chunks_size:
    distribution: int_uniform
    min: 1
    max: 50
  epsilon_final_at:
    distribution: int_uniform
    min: 10000
    max: 100000
  epsilon_final:
    distribution: uniform
    min: 0.01
    max: 0.1
  epsilon:
    distribution: uniform
    min: 0.1
    max: 1.0








