program: car_racing.py
name: car-racing
method: bayes
metric:
  goal: maximize
  name: eval_reward
parameters:
  n_steps:
    value: 100000
  epsilon_final_at:
    value: 100000
  learning_rate:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-1








