program: reinforce_baseline.py
name: reinforce_baseline
method: bayes
metric:
  goal: maximize
  name: final_reward
parameters:
  learning_rate:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-1
  gamma:
    distribution: uniform
    min: 0.8
    max: 1.0
  hidden_layer_size:
    distribution: int_uniform
    min: 4
    max: 1024
  batch_size:
    distribution: int_uniform
    min: 1
    max: 32








